### ISSUE TITLE
Support array and list attributes

### ISSUE THREAD

**Issue by superstar54** [superstar54/beautiful-atoms#102]
Problem
==========

In Blender, an attribute is a generic term to describe data stored per-element in a geometry data-block. In the case of Batoms,  an attribute is data associated with every atom. The data can be an int, float, string,  boolean, 3D or 3D vector. https://docs.blender.org/api/current/bpy.types.Attribute.html.

However, many other properties may have other types, e.g. 3x3 tensor (2D np.arrays) in magres files. We need a proposal to handle this.

Proposal
===========

Scatter data
-------------------
One idea is separate the arrays into individual floats. For example, convert a 3x3 tensor to 9 attributes: a11, a12, a13, a21, a22, a23, a31, a32, a33.

We define an `Attribute` class:

``` python
class Attribute:
    def __init__(self, datatype = "INT", shape = (1)) -> None:
        self.type = datatype
        self.shape = shape


```

For a 2D array (list), name of the new attributes are 

```python
n, m = array.shape
for i in range(n):
    for j in range(m):
        new_name = "name{i}{j}"
````

Gather data
------------------------
Gather all data by the new attribute name

**Comment by alchem0x2A** [comment]
agreed. It seems blender's attribute types are hardcoded c-types so they appear less flexible (only 2D or 3D vectors allowed). The scatter-gather approach should in principle work more flexible but we may want to do some performance benchmark later.

**Comment by alchem0x2A** [comment]
Another approach I'm thinking is to save the json-formatted string of the tensor value and add as `StringAttribute` to the node. This will of course only affect the loading / saving of the model but during the python process we always operate on the matrix. But maybe not very elegant solution
