### ISSUE TITLE
[Bug] Wrong binary search in `install.py` when run under WSL

### ISSUE THREAD

**Issue by alchem0x2A** [superstar54/beautiful-atoms#104]
**Describe the bug**
Running `install.py` will cause the installer to look for the blender file hierachy like in Linux (but need to be Windows-specific)

**To Reproduce**
1. Normal Blender 3.1 installation, running `install.py` in WSL2. 

**Expected behavior**
Installation script report error
```
(beautiful_atoms) user@LAPTOP-RF6VNHSJ:/mnt/c/Users/18188/repos/beautiful-atoms$ $CONDA_PYTHON_EXE install.py "/mnt/c/Program Files/Blender Foundation/Blender 3.1/"  --use-startup --use-preferences
Namespace(blender_root='/mnt/c/Program Files/Blender Foundation/Blender 3.1/', conda_env_name=None, dependency_only=False, generate_env_file=None, local_repo_path=PosixPath('/mnt/c/Users/18188/repos/beautiful-atoms'), plugin_version='main', uninstall=False, use_pip=False, use_preferences=True, use_startup=True)
You're running install.py script using python interpreter:
/home/bwander/anaconda3/bin/python
It may be updated during the install process and causing issues. We recommend using another python interpreter for install.py, such as:
$CONDA_PYTHON_EXE install.py [options]
Continue? [y/N]y
Traceback (most recent call last):
  File "install.py", line 1073, in <module>
    main()
  File "install.py", line 999, in main
    true_blender_bin = _get_blender_bin(os_name, true_blender_root)
  File "install.py", line 215, in _get_blender_bin
    f"Cannot find blender binary at {blender_bin.as_posix()}"
FileNotFoundError: Cannot find blender binary at /mnt/c/Program Files/Blender Foundation/blender
```

**Comment by alchem0x2A** [comment]
Possible Solutions:
1. Detect if WSL flag exists in `/proc/version` (what about other systems like Cygwin?) May be harder to implement all situations
2. Add an alternative search path in linux, if default does blender bin does not exist (need to update the lib path as well)
3. Add a flag to force tag OS type in `install.py`

**Comment by alchem0x2A** [comment]
quick test on the values of `sys.platform` on windows
1. MingGW64 (git bash shell): `win32`
2. Cygwin: `win32`
3. WSL / WSL2: `linux`

so it seems the problem is unique to WSL, while any other linux-like shell emulator on windows should work fine.

**Comment by alchem0x2A** [comment]
I realized in any case the user should not mix a windows-based blender installation while running installation script in WSL since the wheels installed via conda will be wrong.

There is little we can do to detect the error apart from explicitly state in the doc. I can add a special case when `os_name == "linux"` but `Program Files` found in the path.

**Comment by superstar54** [comment]
I don't quite understand the path here:
``` bash
"/mnt/c/Program Files/Blender Foundation/Blender 3.1/"
```
Does it mean WSL using the Blender installed on Windows?

For people using WSL, I think they should follow the "Linux" installation exactly. Therefore, one first installs a Blender inside WSL, then provides the path for the installation:
``` bash
$CONDA_PYTHON_EXE install.py ~/apps/Blender/3.1  --use-startup --use-preferences
```

I don't familiar with WSL and don't have one at hand. Maybe I was wrong about this.

**Comment by alchem0x2A** [comment]
exactly. this error msg comes from one of my colleague and I later realized it's a wrong mixup between WSL and windows installation. PR #109 just adds additional msg about this. I think we don't need to do anything more to modify the install script.

another PR https://github.com/superstar54/beautiful-atoms-docs/pull/16 adds warning in the doc. I think that should be sufficient for the information. I appreciate you take a look. We can close this issue after the doc is merged too

**Comment by superstar54** [comment]
The documentation has been updated.
