### ISSUE TITLE
[Bug] Cannot load ase atoms with `np.int32` arrays

### ISSUE THREAD

**Issue by alchem0x2A** [superstar54/beautiful-atoms#105]
**Describe the bug**
Currently `ObjectGN.set_attibutes` prevents an ase Atoms with arrays of `np.int32` dtype to be loaded. Such atoms may be read from a customized extxyz file if the field identifier is `I`.

**To Reproduce**
Consider the following extxyz file of an methane molecule 
```
5
Lattice="7 0 0 4.28626e-16 7 0 4.28626e-16 4.28626e-16 7" Properties=species:S:1:pos:R:3:some_flag:I:1
C      3.81252    1.77729    1.14841    1
H      3.01596    1.19028    1.55563    2
H      3.66167    1.90241    0.09651    2
H      3.82769    2.73612    1.62309    2
H      4.74475    1.28036    1.31843    2
```

`ase.io.read` will create an atoms object and convert the last column to an array `some_flag` of `np.int32` dtype. Since on most recent 64bit platforms `int` is default to `np.int64`, comparing `np.issubdtype` will fail in this case, preventing the ObjectGN to be created.

In principle such error may happen for other format io too, if there is an explicit `np.int32` array added to Atoms object.

Typical error output

```
Traceback (most recent call last):
  File "/Users/ttian/Documents/Dev/beautiful-atoms/tests/test_batoms.py", line 339, in <module>
    test_batoms_array()
  File "/Users/ttian/Documents/Dev/beautiful-atoms/tests/test_batoms.py", line 324, in test_batoms_array
    atoms_bl = read("../tests/datas/ch4_int_flag.extxyz")
  File "/Applications/Blender.app/Contents/Resources/3.1/scripts/addons_contrib/batoms/bio/bio.py", line 27, in read
    batoms = Batoms(label=label, from_ase=atoms)
  File "/Applications/Blender.app/Contents/Resources/3.1/scripts/addons_contrib/batoms/batoms.py", line 166, in __init__
    self.build_object(label, arrays, location)
  File "/Applications/Blender.app/Contents/Resources/3.1/scripts/addons_contrib/batoms/batoms.py", line 246, in build_object
    self.set_attributes(arrays)
  File "/Applications/Blender.app/Contents/Resources/3.1/scripts/addons_contrib/batoms/base/object.py", line 430, in set_attributes
    raise KeyError('%s is not supported.' % dtype)
KeyError: "<class 'numpy.int32'> is not supported."
```
<img width="732" alt="image" src="https://user-images.githubusercontent.com/6829706/171311476-74727cc5-a3b4-4d9c-a5a9-2ab2819b869f.png">

**Solutions**

Use more arbitrary types `np.integer` and `np.float` in `ObjectGN.set_attributes`, as indicated in the numpy doc https://github.com/numpy/numpy/blob/db481babcfa7ebc70833e77985858e9295a3135b/numpy/core/numerictypes.py#L357

**Comment by superstar54** [comment]
This is actually an important issue. There are more types that need to be handled, e.g. boolean, 3D vector (velocities), (3x3 matrix (stress). 
When loading data to Blender, only positions are explicitly saved as the positions of the vertices. All other per-atom properties (element, velocities, stress, other tags ...) should be saved as the attributes of the vertices. Otherwise, all the python variables will be lost when the terminal session is closed. 
The problem is that Blender only allows a few simple data types for its attribute. Please also see #102 . I am working on this, and will make a PR soon.
