### ISSUE TITLE
[enhancement] universal installation script

### ISSUE THREAD

**Issue by alchem0x2A** [superstar54/beautiful-atoms#17]
Continuation to #11 but to provide a universal script for installation on host platform or to build docker image.
Ideas can be similar to https://github.com/compas-dev/compas/blob/main/src/compas_blender/install.py.

Desired installation method using the universal script (via conda environment)
```
# optional create the conda environment
conda create -n beautiful_atoms && conda activate beautiful_atoms
curl -O <github_url_to_installation_script.sh>
# Inspect the content of script
sh installation.sh
```
installation script will try to link current conda environment to blender's python root and add the stable version of batoms plugin.

Desired uninstallation method
```
curl -O <github_url_to_uninstall_script.sh>
# Inspect the content of script
sh uninstall.sh
```
uninstallation restores the python root for blender and removes batoms plugin.

**Comment by alchem0x2A** [comment]
while current documentations about pip remain valid, the conda installation part can be merged into one section about the universal installation script

TODOs:
- [ ] installation / unstall scripts
- [ ] cross-platform test actions
- [ ] env.yaml for conda

**Comment by superstar54** [comment]
@alchem0x2A  This will be great. Once this has been implemented, please update the documentation in https://github.com/superstar54/beautiful-atoms-docs/tree/main/docs/source/install

**Comment by alchem0x2A** [comment]
a recent bug issue tracks the incompatibility between anaconda and other programs which may not use its default activation script on window https://github.com/ContinuumIO/anaconda-issues/issues/11994 Until the upstream is resolved, installation script force user to use pip on windows
