### ISSUE TITLE
[Improvement] Containerize batoms and Blender environment?

### ISSUE THREAD

**Issue by alchem0x2A** [superstar54/beautiful-atoms#2]
@superstar54 Great work! I checked the recent dev of the repo and amazed by how much you have achieved. Would you consider providing a containerized environment with `batoms`- enabled blender inside docker as a potential installation method? For a new user the current installation could be a bit challenging (e.g. `spglib` is not easily built on an ARM machine via pip, or user may experience conflicting python versions in conda). The dockerized environment (with `batoms` and `batoms_api` combined) can benefit users if they just use beautiful-atoms as a drop-in replacement for `ase.visualize`.

If you're interested I can make a PR with the current code tree. Kindly let me know if you have any suggestions!

**Comment by superstar54** [comment]
Thanks! That's a good idea. I am not familiar with the dockerized environment. Please make a PR and give it a try.
