### ISSUE TITLE
Attribute Error during the test of installation

### ISSUE THREAD

**Issue by psi-cmd** [superstar54/beautiful-atoms#20]
## The problem (procedure)

1. `pip install ase scikit-image` with builtin python

2. enable the plugin

3. test as instruction:

    ```python
    from batoms import Batoms
    h2o = Batoms('h2o', species = ['O', 'H', 'H'],
        positions= [[0, 0, 0.40], [0, -0.76, -0.2], [0, 0.76, -0.2]])
    ```
    and the traceback is as follows:
    ```
    Traceback (most recent call last):
      File "<blender_console>", line 1, in <module>
      File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\batoms\batoms.py", line 143, in __init__
        self._cell = Bcell(label, cell, batoms=self)
      File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\batoms\cell.py", line 38, in __init__
        self.build_object(array, location)
      File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\batoms\cell.py", line 72, in build_object
        self.build_geometry_node()
      File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\batoms\cell.py", line 91, in build_geometry_node
        JoinGeometry.outputs['Geometry'], GroupOutput.inputs['Geometry'])
    AttributeError: 'NoneType' object has no attribute 'inputs'
    ```

## Environment

* beautiful-atoms: release-2.0.0
* Blender: 3.0.1
* Python in Blender: 3.9.7

**Comment by superstar54** [comment]
This is a strange error. Because the ``GroupOutput`` shouldn't be None. Which Windows system do you use?

Could you please add the following lines to File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\batoms\cell.py", before line 91, and share the output here. Thanks.
``` python
        print(self.obj)
        print(len(self.obj.data.vertices))
        print(gn)
        print(GroupOutput)
        print(GroupInput)
```

**Comment by psi-cmd** [comment]
```
<bpy_struct, Object("h2o_cell") at 0x00000281169FEB08>
8
<bpy_struct, NodesModifier("GeometryNodes_h2o_cell") at 0x0000028116B353C8>
None
None
```
My vscode is not configured for blender python debugging, or I may provide something more precise.

**Comment by superstar54** [comment]
Please add another line:
``` python
        print(gn.node_group.nodes[:])
```
And share the output. Thanks

**Comment by psi-cmd** [comment]
```
<bpy_struct, Object("h2o_cell") at 0x000002859FB32408>
8
<bpy_struct, NodesModifier("GeometryNodes_h2o_cell") at 0x000002859FC45548>
None
None
[bpy.data.node_groups['GeometryNodes_h2o_cell'].nodes["组输入"], bpy.data.node_groups['GeometryNodes_h2o_cell'].nodes["组输出"], bpy.data.node_groups['GeometryNodes_h2o_cell'].nodes["h2o_JoinGeometry"]]
```
The language setting influenced the key name, it's better to fix the language to English.

It works after changing the language to English, thanks so much!

**Comment by superstar54** [comment]
I pushed a patch to fix the language-related error. Now you can use the Chinese version. Please have a try. Please download the latest version:  

https://github.com/superstar54/beautiful-atoms/archive/refs/heads/main.zip

and then extract the file, and move the folder ``batoms`` to Blender addons folder.
