### ISSUE TITLE
vertex group to individual object

### ISSUE THREAD

**Issue by mmw0909** [superstar54/beautiful-atoms#42]
Hi Xing, Thanks for developing this wonderful tool. Based on my understanding, the supercell of atoms is basically created by duplicating the atom_instance to a vertex group. But is there any way I can split the vertex group into individual objects and make modifications to each individual atom?

**Comment by superstar54** [comment]
Yes. You can set different species for the same element. Please visit this:
https://beautiful-atoms.readthedocs.io/en/latest/tutorial/species.html

If you are good at Blender scripting, there is another method: using the `Realize Instances Node`. 
https://docs.blender.org/manual/en/latest/modeling/geometry_nodes/instances/realize_instances.html
You can add a `Realize Instances Node` in the Geometry node of the batoms object. I didn't implement this inside Beautiful-atoms, because the performance can become much worse for large systems.

How large is your system?  What kind of modifications do you want to make?

**Comment by mmw0909** [comment]
Hi Xing, thanks for the swift response. The first method you quote doesn't seem to apply to my situation. What I want to do is to apply the boolean modifier between one of the atoms in the supercell and another different object I added, for example, the cone and the atom beneath it. For it to work, I have to be able to select the atom. Do you have any suggestions? I am completely new to Blender, thanks a lot for your information. 

<img width="493" alt="Screen Shot 2022-03-16 at 20 41 12" src="https://user-images.githubusercontent.com/58865632/158714191-daf2fa36-f7da-46ab-a8ed-666e7e1e5f63.png">

**Comment by mmw0909** [comment]
Hi Xing, I just tried the realize instances node. It first gave an error saying node can't be applied to geometry with shape keys. After removing the shape keys, it still didn't work. 
<img width="718" alt="Screen Shot 2022-03-16 at 21 30 18" src="https://user-images.githubusercontent.com/588656
<img width="1727" alt="Screen Shot 2022-03-16 at 21 31 08" src="https://user-images.githubusercontent.com/58865632/158718646-d6cb96c6-c5b1-4e6f-a04d-a8b2fd40fac5.png">
32/158718616-8861d4b9-47e4-4497-a945-23ce07de6825.png">

**Comment by superstar54** [comment]
Hi. Before realizing the instance, a batoms object is only a group of vertices without edge and face. Thus the bealean modifier can not work on it. Almost all the modifiers need to work on the edge and face.

After realizing the instance, an atom becomes a sphere mesh, not a single point anymore. Thus the bealean modifier makes unrealistic geometry (e.g. broken sphere), which is unphysical. Here is a video:

https://user-images.githubusercontent.com/11457659/158761688-ca58e270-26db-4a5f-84bc-06edd688c030.mp4


If you only want to select individual atoms and delete them. Try to delete the vertices directly. Here is a video:

https://user-images.githubusercontent.com/11457659/158763540-fff1ef30-d0e5-49f4-a5dd-438a61a45e61.mp4

Hope this could help.

**Comment by mmw0909** [comment]
Hi Xing, Thanks so much! This is very helpful! I think I can work it out with the method you showed. But just out of curiosity, even after the geometry to instance, all the atoms still appear to be one object, is there any way to make each atom their own object at their location in the supercell (instead of setting different species for the same element)?

**Comment by superstar54** [comment]
Currently, batoms does not support splitting every atom into one object. Blender is not good at handling a large number of objects. Thus the performance could be much worse. Batoms use the newly developed Geometry node, which offers both flexibility and good performance.

Please look at this addon. It uses the traditional `Instancing` method, which supports `make instances real` to make each atom an object.
https://docs.blender.org/manual/en/latest/addons/import_export/mesh_atomic.html
