### ISSUE TITLE
Error running the gallery_high_order_bond.py demonstration

### ISSUE THREAD

**Issue by Jeff-oakley** [superstar54/beautiful-atoms#55]
When I run the following command as demonstrated in the gallery scripts, it gives the following errors:

```
plane = draw_plane(location = [0, 0, c6h6.get_all_vertices()[:, 2].min() - c6h6['C'].size[0]], 
...             size = 400, color = (0.4, 0.4, 0.4, 1))
```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
AttributeError: 'Species' object has no attribute 'size

I realize size is not an attribute of batoms.bspecies.Species

**Comment by superstar54** [comment]
Thanks for the report. The error is because the documentation is out of date. I have updated it. It should be fixed now. Please try it again.
