### ISSUE TITLE
Error after installing the addon

### ISSUE THREAD

**Issue by kalimeroo** [superstar54/beautiful-atoms#85]
After installing the addon as documented in the docs, when I try to add an atom in Blender I get the following error :

  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\batoms\utils\butils.py", line 266, in get_nodes_by_name
    node = nodes.new(type)
RuntimeError: Error: Node type FunctionNodeCompareFloats undefined

location: <unknown location>:-1

**Comment by superstar54** [comment]
Thanks for the report. This is a bug that occurs when using the latest version of Blender ( 3.1.1 or 3.1.2). I have fixed this in a new PR. Please download the latest version of Beautiful Atoms and have a try.

**Comment by kalimeroo** [comment]
Latest version fixes most of the issue with Belnder > 3.1.0. I can import atoms, CIF, pdb,...
Only when I try to add a molecule (Shift+A->Add molecule) this causes Blender to crash

**Comment by superstar54** [comment]
I can confirm the crash on a Win 10 system. However, this does not occur on my Ubuntu system. It should be a system-specific bug of Blender. 
I managed to fix the crash on Win10 temporarily in a new PR (by some meaningless rearrangement of a for loop). Please download the latest version of Beautiful Atoms and try. If Blender continues to crash, please use version 3.1.0 or 3.0.0.
